apiVersion: v1
kind: ConfigMap
metadata:
  name: kwatch
  namespace: kube-monitor
data:
  config.yaml: |
    alert:
      teams:
          webhook: https://myteamsweebhook
    namespaces:
      - app
      - !kube-system
      - !kube-public
      - !kube-node-lease
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kwatch
rules:
- apiGroups: [""]
  resources: ["events", "nodes", "nodes/proxy", "pods", "pods/log", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "statefulsets", "deployments", "replicasets"]
  verbs: ["get", "watch", "list"]
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kwatch
  namespace: kube-monitor
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kwatch
subjects:
  - kind: ServiceAccount
    name: kwatch
    namespace: kube-monitor
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwatch
  namespace: kube-monitor
spec:
  selector:
    matchLabels:
      app: kwatch
  template:
    metadata:
      labels:
        app: kwatch
    spec:
      restartPolicy: Always
      serviceAccountName: kwatch
      containers:
      - name: kwatch
        image: ghcr.io/abahmed/kwatch:v0.10.1
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /config
        env:
          - name: CONFIG_FILE
            value: "/config/config.yaml"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config-volume
        configMap:
          name: kwatch
