apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  name: "k8s-master1"
  taints:
    - key: "kubeadmNode"
      value: "master"
      effect: "NoSchedule"
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
  ignorePreflightErrors:
    - IsPrivilegedUser
localAPIEndpoint:
  advertiseAddress: "10.10.10.10"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  local:
    imageRepository: "k8s.gcr.io"
    imageTag: "3.4.13-0"
    dataDir: "/var/lib/etcd"
    external:
      endpoints:
      - "10.10.10.11:2379"
      - "10.10.10.12:2379"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "192.168.0.0/16"
  dnsDomain: "cluster.local"
kubernetesVersion: "v1.21.5"
controlPlaneEndpoint: "10.10.10.10:6443"
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
imageRepository: "k8s.gcr.io"
useHyperKubeImage: false
clusterName: "oktaysavdi-cluster"
